//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_skirmishes
    {
        public int id { get; set; }
        public Nullable<int> league_round { get; set; }
        public Nullable<System.DateTime> skirmish_date { get; set; }
        public Nullable<System.DateTime> admin_date { get; set; }
        public Nullable<int> id_mission { get; set; }
        public Nullable<int> id_region { get; set; }
    }
}
