//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_die_faces
    {
        public int id { get; set; }
        public Nullable<int> id_die_type { get; set; }
        public Nullable<int> die_face { get; set; }
        public string action { get; set; }
        public string info { get; set; }
        public Nullable<int> cost_credits { get; set; }
        public Nullable<int> sell_materials { get; set; }
        public Nullable<int> sell_credits { get; set; }
        public string open_url { get; set; }
    }
}
