//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_troops
    {
        public int id { get; set; }
        public Nullable<int> id_game_faction { get; set; }
        public string name { get; set; }
        public string conflict_rule { get; set; }
        public string cost { get; set; }
        public string upkeep { get; set; }
        public string notes { get; set; }
        public string starting { get; set; }
    }
}
