//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_user_dice
    {
        public int id { get; set; }
        public Nullable<int> id_user_league { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> id_die_type { get; set; }
        public Nullable<System.DateTime> spent_date { get; set; }
        public Nullable<int> resources_gained { get; set; }
        public Nullable<System.DateTime> rolled_date { get; set; }
        public Nullable<int> id_die_face { get; set; }
        public Nullable<int> id_message { get; set; }
    }
}
