//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_user_dice_msg
    {
        public int id { get; set; }
        public Nullable<int> id_user_dice { get; set; }
        public Nullable<int> id_user_from { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> message_date { get; set; }
    }
}
