//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercs_skirmish_user_troops
    {
        public int id { get; set; }
        public Nullable<int> id_skirmish_user { get; set; }
        public Nullable<int> id_user_troop { get; set; }
        public Nullable<int> enemies_killed { get; set; }
        public Nullable<int> enemies_wounded { get; set; }
        public Nullable<int> kit1_spent { get; set; }
        public Nullable<int> kit2_spent { get; set; }
        public string troop_status { get; set; }
    }
}
