//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_regions
    {
        public int id { get; set; }
        public string name { get; set; }
        public string info { get; set; }
        public string color_hexcode { get; set; }
        public string reward { get; set; }
    }
}
