//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MANAGERDBEntities : DbContext
    {
        public MANAGERDBEntities()
            : base("name=MANAGERDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mercs_die_types> mercs_die_types { get; set; }
        public DbSet<mercs_faction_dice> mercs_faction_dice { get; set; }
        public DbSet<mercs_troops> mercs_troops { get; set; }
        public DbSet<mercs_upgrades> mercs_upgrades { get; set; }
        public DbSet<mercs_user_troops> mercs_user_troops { get; set; }
        public DbSet<t_badges> t_badges { get; set; }
        public DbSet<t_game_factions> t_game_factions { get; set; }
        public DbSet<t_games> t_games { get; set; }
        public DbSet<t_league_titles> t_league_titles { get; set; }
        public DbSet<t_leagues> t_leagues { get; set; }
        public DbSet<t_syslog> t_syslog { get; set; }
        public DbSet<t_systables> t_systables { get; set; }
        public DbSet<t_user_leagues> t_user_leagues { get; set; }
        public DbSet<t_user_titles> t_user_titles { get; set; }
        public DbSet<t_users> t_users { get; set; }
        public DbSet<mercs_user_upgrades> mercs_user_upgrades { get; set; }
        public DbSet<mercs_die_faces> mercs_die_faces { get; set; }
        public DbSet<t_messages> t_messages { get; set; }
    }
}
