//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_messages
    {
        public int id { get; set; }
        public Nullable<int> id_user_from { get; set; }
        public Nullable<int> id_user_to { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> sent_date { get; set; }
        public Nullable<System.DateTime> read_date { get; set; }
        public Nullable<int> id_league { get; set; }
        public Nullable<int> round { get; set; }
        public string status { get; set; }
    }
}
