//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_titles
    {
        public int id { get; set; }
        public Nullable<int> id_user_league { get; set; }
        public Nullable<int> id_league_title { get; set; }
        public Nullable<System.DateTime> unlock_date { get; set; }
    }
}
