//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_users
    {
        public int id { get; set; }
        public Nullable<int> numero_socio { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string avatar_url { get; set; }
        public string info { get; set; }
        public Nullable<int> login_errors { get; set; }
        public Nullable<int> security_level { get; set; }
        public string active { get; set; }
    }
}
